version: '2'
services:
  spring-rewardpoint-rest-rewardpoint:
    image: 730329488449.dkr.ecr.us-west-2.amazonaws.com/spring-rewardpoint-rest-rewardpoint
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8090:8080"
